name: Deploy Frontend to Nginx Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd client
          npm install

      - name: Build frontend
        run: |
          cd client
          CI=false npm run build

      - name: Copy files to remote server via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "client/build/"
          target: "/tmp/frontend-build"
          strip_components: 0
          debug: true

      - name: Deploy to Nginx folder
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            sudo mkdir -p /tmp/frontend-build
            sudo rm -rf /var/www/html/*
            sudo cp -a /tmp/frontend-build/. /var/www/html/
            sudo nginx -t && sudo systemctl restart nginx
